/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'auth.login': RouteRecordInfo<
      'auth.login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'auth.register': RouteRecordInfo<
      'auth.register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'class-rule.detail': RouteRecordInfo<
      'class-rule.detail',
      '/class-rule/:ruleId',
      { ruleId: ParamValue<true> },
      { ruleId: ParamValue<false> },
      | never
    >,
    'class-rule.edit': RouteRecordInfo<
      'class-rule.edit',
      '/class-rule/:ruleId/edit',
      { ruleId: ParamValue<true> },
      { ruleId: ParamValue<false> },
      | never
    >,
    'class-rule.create': RouteRecordInfo<
      'class-rule.create',
      '/class-rule/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'course.detail': RouteRecordInfo<
      'course.detail',
      '/course/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | 'course.session.detail'
    >,
    'course.session.detail': RouteRecordInfo<
      'course.session.detail',
      '/course/:id/session/:sessionId',
      { id: ParamValue<true>, sessionId: ParamValue<true> },
      { id: ParamValue<false>, sessionId: ParamValue<false> },
      | never
    >,
    'course.add-student': RouteRecordInfo<
      'course.add-student',
      '/course/:id/add-student',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'course.edit': RouteRecordInfo<
      'course.edit',
      '/course/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'course.list': RouteRecordInfo<
      'course.list',
      '/course',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'course.create': RouteRecordInfo<
      'course.create',
      '/course/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard': RouteRecordInfo<
      'dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'enrollment.detail': RouteRecordInfo<
      'enrollment.detail',
      '/enrollment/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'session': RouteRecordInfo<
      'session',
      '/session',
      Record<never, never>,
      Record<never, never>,
      | 'session.edit'
    >,
    'session.edit': RouteRecordInfo<
      'session.edit',
      '/session/edit/:ruleId',
      { ruleId: ParamValue<true> },
      { ruleId: ParamValue<false> },
      | never
    >,
    'student.detail': RouteRecordInfo<
      'student.detail',
      '/student/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'student.add-course': RouteRecordInfo<
      'student.add-course',
      '/student/:id/add-course',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'student.edit': RouteRecordInfo<
      'student.edit',
      '/student/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'student.list': RouteRecordInfo<
      'student.list',
      '/student',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'student.create': RouteRecordInfo<
      'student.create',
      '/student/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/auth/login.vue': {
      routes:
        | 'auth.login'
      views:
        | never
    }
    'src/pages/auth/register.vue': {
      routes:
        | 'auth.register'
      views:
        | never
    }
    'src/pages/class-rule/[ruleId].vue': {
      routes:
        | 'class-rule.detail'
      views:
        | never
    }
    'src/pages/class-rule/[ruleId].edit.vue': {
      routes:
        | 'class-rule.edit'
      views:
        | never
    }
    'src/pages/class-rule/create.vue': {
      routes:
        | 'class-rule.create'
      views:
        | never
    }
    'src/pages/course/[id].vue': {
      routes:
        | 'course.detail'
        | 'course.session.detail'
      views:
        | 'default'
    }
    'src/pages/course/[id]/session/[sessionId].vue': {
      routes:
        | 'course.session.detail'
      views:
        | never
    }
    'src/pages/course/[id].add-student.vue': {
      routes:
        | 'course.add-student'
      views:
        | never
    }
    'src/pages/course/[id].edit.vue': {
      routes:
        | 'course.edit'
      views:
        | never
    }
    'src/pages/course/list.vue': {
      routes:
        | 'course.list'
      views:
        | never
    }
    'src/pages/course/create.vue': {
      routes:
        | 'course.create'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | 'dashboard'
      views:
        | never
    }
    'src/pages/enrollment/[id].vue': {
      routes:
        | 'enrollment.detail'
      views:
        | never
    }
    'src/pages/session.vue': {
      routes:
        | 'session'
        | 'session.edit'
      views:
        | 'default'
    }
    'src/pages/session/edit/[ruleId].vue': {
      routes:
        | 'session.edit'
      views:
        | never
    }
    'src/pages/student/[id].vue': {
      routes:
        | 'student.detail'
      views:
        | never
    }
    'src/pages/student/[id].add-course.vue': {
      routes:
        | 'student.add-course'
      views:
        | never
    }
    'src/pages/student/[id].edit.vue': {
      routes:
        | 'student.edit'
      views:
        | never
    }
    'src/pages/student/list.vue': {
      routes:
        | 'student.list'
      views:
        | never
    }
    'src/pages/student/create.vue': {
      routes:
        | 'student.create'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
