/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/course/[id].edit': RouteRecordInfo<
      '/course/[id].edit',
      '/course/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/course/create': RouteRecordInfo<
      '/course/create',
      '/course/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/course/list': RouteRecordInfo<
      '/course/list',
      '/course/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/session': RouteRecordInfo<
      '/session',
      '/session',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/student/[id].edit': RouteRecordInfo<
      '/student/[id].edit',
      '/student/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/student/create': RouteRecordInfo<
      '/student/create',
      '/student/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/student/list': RouteRecordInfo<
      '/student/list',
      '/student/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/course/[id].edit.vue': {
      routes:
        | '/course/[id].edit'
      views:
        | never
    }
    'src/pages/course/create.vue': {
      routes:
        | '/course/create'
      views:
        | never
    }
    'src/pages/course/list.vue': {
      routes:
        | '/course/list'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
    }
    'src/pages/session.vue': {
      routes:
        | '/session'
      views:
        | never
    }
    'src/pages/student/[id].edit.vue': {
      routes:
        | '/student/[id].edit'
      views:
        | never
    }
    'src/pages/student/create.vue': {
      routes:
        | '/student/create'
      views:
        | never
    }
    'src/pages/student/list.vue': {
      routes:
        | '/student/list'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
